require_relative 'generative/variatio'
require_relative 'generative/darwin'
require_relative 'generative/backboner'
require_relative 'generative/markov'
require_relative 'generative/generative-grammar'
