AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false

# Relajar restricciones comunes
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 120
