# RBS for core-ext/array-explode-ranges.rb - ExplodeRanges refinement
#
# NOTE: RBS does not support Ruby refinements. These methods are added via
# `using Musa::Extension::ExplodeRanges` and won't provide type checking.

module Musa
  module Extension
    # Refinement that expands Range objects within arrays.
    #
    # Methods available via refinement:
    # - Array#explode_ranges -> Array
    module ExplodeRanges
    end
  end
end

# Extended Array methods (via refinement)
# Available when `using Musa::Extension::ExplodeRanges`
class Array[unchecked out Elem]
  # Expands all Range objects in array to their constituent elements.
  # Available via refinement: `using Musa::Extension::ExplodeRanges`
  # def explode_ranges: () -> Array[untyped]
end
